# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hotel', models.CharField(max_length=30)),
                ('release_date', models.DateField()),
                ('how_much', models.IntegerField()),
            ],
        ),
    ]
